version: 1.1.{build}

os: Visual Studio 2015
platform: Any CPU
configuration: Release
build:
  project: DotOPDS.sln
init:
  - ps: $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 7)
before_build:
  - ps: nuget restore
after_build:
  - 7z a DotOPDS.zip %APPVEYOR_BUILD_FOLDER%\DotOPDS\bin\Release\* -r -x!*.pdb -x!*.xml -x!FSharp.Core.dll
  - 7z a DotOPDS-pdb.zip %APPVEYOR_BUILD_FOLDER%\DotOPDS\bin\Release\* -r -x!*.xml -x!*.dll -x!*.exe -x!*.config

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(GIT_HASH)-$(APPVEYOR_REPO_BRANCH)'

shallow_clone: true
cache:
  - packages -> **\packages.config

test: off

artifacts:
  - path: 'DotOPDS.zip'
    name: release_archive
  - path: 'DotOPDS-pdb.zip'
    name: debug_symbols

deploy:
- provider: GitHub
  auth_token:
    secure: TxP8eEzFcS3XuTx/zRKV4Pev1x6D4egsnIoonP6ArBpqFy5V50DwgrRnIMETEN56
  artifact: release_archive,debug_symbols
  draft: true
  force_update: true
  on:
    appveyor_repo_tag: true
